#!/usr/bin/env bash
#
# A small shell script which prints all files quarantined by gadi in the format
# required by the file recovery tool.
#
# No arguments are required to run this script.
#
# Example Usage:
#
# ./list-quarantined-files >quarantine.list
# nci-file-expiry quarantine.list
# rm quarantine.list
#
set -euo pipefail

# tr -s will collapse multiple consecutive whitespace characters into a single
# whitespace character. This is important for cut.
nci-file-expiry list-quarantined | tail -n +2 | tr -s ' ' | cut -d' ' -f1,6
